import turtle as trtl

painter = trtl.Turtle()

painter.pensize(2)
painter.pencolor('black')
painter.begin_fill()
painter.fillcolor('red')
painter.goto(25,0)
painter.goto(-25,0)
painter.goto(-25,200)
painter.goto(25,200)
painter.goto(25,0)
painter.end_fill()
painter.pencolor('black')
painter.begin_fill()
painter.fillcolor('blue')
painter.goto(50,0)
painter.left(45)
painter.goto(25,75)
painter.end_fill()
painter.pencolor('black')
painter.goto(25,0)
painter.goto(-25,0)
painter.pencolor('black')
painter.begin_fill()
painter.fillcolor('blue')
painter.goto(-50,0)
painter.left(45)
painter.goto(-25,75)
painter.end_fill()
painter.pencolor('black')
painter.goto(-25,200)
painter.pencolor('black')
painter.begin_fill()
painter.fillcolor('blue')
painter.right(45)
painter.forward(35)
painter.right(90)
painter.goto(25,200)
painter.end_fill()
painter.penup()
painter.goto(-8,150)
painter.pendown()
painter.pencolor('green')
painter.begin_fill()
painter.fillcolor('white')
painter.circle(10)
painter.end_fill()
painter.penup()
painter.goto(150,-250)
painter.pendown()
painter.pencolor('#90c0df')
painter.begin_fill()
painter.fillcolor('#90c0df')
painter.circle(45)
painter.end_fill()
painter.penup()
painter.goto(155,-250)
painter.pendown()
painter.begin_fill()
painter.fillcolor('white')
painter.circle(10)
painter.end_fill()
painter.penup()
painter.goto(-150,250)
painter.pencolor('yellow')
painter.pendown()
painter.begin_fill()
painter.fillcolor('yellow')
painter.circle(45)
painter.end_fill()








window = trtl.Screen()
window.mainloop()

